/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HeadersSchema {
  "X-Idempotency-Key"?: string;
  "X-Hub-Signature": string;
  "User-Agent"?: string;
  "Content-Type"?: string;
}
